name: Do update

on:
  schedule:
    - cron: '21 0 * * fri'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv install
    - name: Scrape wiki
      run: |
        pipenv run python main.py
        mv npcs-dps-calc.min.json npcs-dps-calc.min.json.bak
        mv items-dps-calc.min.json items-dps-calc.min.json.bak
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 8
    - name: Transform results
      run: |
        git checkout --force filtering
        mv npcs-dps-calc.min.json.bak npcs-dps-calc.min.json
        sbt run
    - name: Copy to target branch
      run: |
        mv npc-base-ids.min.json npc-base-ids.min.json.bak
        mv npcs.min.json npcs.min.json.bak
        git checkout --force wiki-data
        mv npcs.min.json.bak npcs.min.json
        mv npc-base-ids.min.json.bak npc-base-ids.min.json
        mv items-dps-calc.min.json.bak items-dps-calc.min.json
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.PAT }}
        path: items-dps-calc.min.json npc-base-ids.min.json npcs.min.json
        branch: wiki-data-${{ steps.date.outputs.date }}
        base: wiki-data
        title: Wiki scrape data ${{ steps.date.outputs.date }}
        commit-message: Wiki scrape data ${{ steps.date.outputs.date }}
    - name: Display output PR
      if: ${{ steps.cpr.outputs.pull-request-number }}
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"